### ISSUE TITLE
Draft a Heilmeier catechism to pitch the main product to be generated in your master by 2021-09-16

### ISSUE THREAD

**Issue by luque82** [luquelab/avogel_master#3]
- Read the Heilmeier catechism introductory documents.
- Answer the key questions with your current knowledge.
- Send the draft to Toni for review and discussion.
- The first draft is due 14 days from now. I can be sent for review earlier. You can get feedback from others prior to the submission if that helps.

**Comment by auroravogel** [comment]
[https://docs.google.com/document/d/12wGrRAIbmv8jkZV_gdAAQ1TW2Ga_0akJGWCdPjApmc8/edit?usp=sharing](url)
